### ISSUE TITLE
Refactoring query parameter in create file

### ISSUE THREAD

**Issue by LeavaTail** [LeavaTail/debugfatfs#4]
**Background**
* debugfatfs support create any file if user execute `create -i` in interactive mode.
* debugfatfs execute query_param from fat/exfat
* query_param prompt user from parameter
* But current implementation is tentative (include magic number, duplicate flow,...)

**TODO**
* [ ] consider data structure and data flow
* [ ] replace new implementaion
* [ ] check test
* [ ] MR to develop branch

**Comment by LeavaTail** [comment]
Discontinue "query parameter"

Ref: https://github.com/LeavaTail/debugfatfs/commit/f4224ce63590ad02c19a23d74ba2193098cb3683
