### ISSUE TITLE
Support new option for TRIM

### ISSUE THREAD

**Issue by LeavaTail** [LeavaTail/debugfatfs#5]
**Background**
* FAT/exFAT filesystem only marked deleted flag when user remove file or directory
* FAT/exFAT can fill in directory entry in deleted entry if deleted area was enough.
* But these flow has overhead to search entry

**Describe the solution you'd like**
* debugfatfs support TRIM command or option
* if user call TRIM command or option, debugfatfs discard unused entry just like fstrim

**design example**
1. check directory entry sequential 
2. if detect deleted entry, rewrite entry to next entry

**TODO**
* [x] consider design
* [x] implement trim function in FAT or exFAT
* [x] implement new option to call trim function
* [x] check test
* [x] MR to develop branch

**Additional context**
